server:
  port: 6035
  
spring:
  application:
    name: one-to-one-service
  config:
    import: configserver:http://localhost:8888
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"  