server:
  port: 8095
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: TRAINING
    url: jdbc:oracle:thin:@10.90.1.107:1521:SIT
    username: TRAINING
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    
