spring:
  application:
    name: vault-config-app
  datasource:
    url: jdbc:oracle:thin:@10.90.1.105:1521/DEV
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
# Vault related configuration

  cloud:
    vault:
      authentication: token
      kv:
        enabled: true
      uri: http://localhost:8200
      token: 00000000-0000-0000-0000-000000000000
  config: 
    import: vault://secret/vault-config-app

      

server:
  port: 8044